development:
  clients:
    default:
      database: zapekanko_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: zapekanko_test
      hosts:
        - localhost:27017
